### ISSUE TITLE
CRA is deprecated

### ISSUE THREAD

**Issue by milkanuch** [L1nkWave/Chat#1]
Wouldn't it be better to use [Next.js](https://nextjs.org/) or [Vite](https://vitejs.dev/)?

**Comment by borjom1** [comment]
It is better to use htmx then xD

**Comment by milkanuch** [comment]
I'm hearing about HTMX for the first time.

It's not like react, on which you want to make an application as I see.
I suggest you change the build tool from CRA to Next.js || Vite.

I think this [page from the blog](https://merge.rocks/blog/create-react-app-vs-next-js-how-are-they-different-and-similar-in-2023) explains my opinion clearly.

**Comment by JeriRov** [comment]
> Wouldn't it be better to use [Next.js](https://nextjs.org/) or [Vite](https://vitejs.dev/)?

I will take your suggestion into account and consider these technologies. Thank you!

**Comment by JeriRov** [comment]
> I'm hearing about HTMX for the first time.
> 
> It's not like react, on which you want to make an application as I see. I suggest you change the build tool from CRA to Next.js || Vite.
> 
> I think this [page from the blog](https://merge.rocks/blog/create-react-app-vs-next-js-how-are-they-different-and-similar-in-2023) explains my opinion clearly.

We have set up our frontend with Nextjs, you can see it [here](https://github.com/L1nkWave/Chat/tree/dev/frontend).

**Comment by milkanuch** [comment]
Good job Space Cowboy 🤠
